module.exports = [
  { _id: "a1", uname: "18-plus",          name: "18+",               pattern: '18\\+|canh nong|bar' },
  { _id: "a2", uname: "5s-online",        name: "5s Online",         pattern: '5s online' },
  { _id: "a3", uname: "am-thuc",          name: "Ẩm thực",           pattern: 'am thuc|che bien|mon an|bua an' },
  { _id: "a4", uname: "ao-thuat",         name: "Ảo thuật",          pattern: 'ao thuat|magic|ao thuat|takayama|magic|dynamo' },
  { _id: "a5", uname: "ban-muon-hen-ho",  name: "Bạn muốn hẹn hò",   pattern: 'ban muon hen ho' },
  { _id: "a6", uname: "bong-da",          name: "Bóng đá",           pattern: 'bong da|messi|neymar|football|ghi ban|ban thang|thu mon|penalty|cau thu|van persie|cu sut|sut phat|lam ban|pha bong|cuu thua|tien dao|trung ve|hau ve|world cup|worldcup|fifa|(ronal\\w+)|re bong|sut truot|copa america|andy cole|da phat|goals?|moc bong|gareth bale|tang bong|di bong|tranh bong' },
  { _id: "a7", uname: "ca-nhac",          name: "Ca nhạc",           pattern: 'ca nhac|nghe roi cam nhận|nghe se nghien|taylor|mv|son tung|bai nay|maroon|nguyen dinh vu|big bang|bigbang|rap|ca khuc|music|ban nhac|mashup|bai hat|hoai lam|khac viet|off?icial|remix|cover|mashup|max volume' },
  { _id: "a8", uname: "canh-giac",        name: "Cảnh giác",         pattern: '' },
  { _id: "a9", uname: "cong-nghe",        name: "Công nghệ",         pattern: 'dong ho|xe may|may tinh bang|iphone|ipad|android|window phone|lumina|sieu xe|che tạo|cong nghe|airline|ferrari|lamborghini|laser|bphone|chiec xe|tuong lua|nam cham|dong co' },
  { _id: "a0", uname: "manga",            name: "Manga",             pattern: 'naruto|onepiece|one piece|anime|sasuke|itachi|madara|hoạt hình|Zoro|Robin|luffy|Larva|Ấu Trùng Tinh Ngịch|Goku|Doreamon|Doramon|Doremon|Doraemon' },
  { _id: "b1", uname: "de-thuong",        name: "Dễ thương",         pattern: 'de thuong|dang yeu|dang iu' },
  { _id: "b2", uname: "doc-la",           name: "Độc & lạ",          pattern: 'chuyen la|ki luc|bi an|doc dao' },
  { _id: "b3", uname: "doi-song-xa-hoi",  name: "Đời sống xã hội",   pattern: 'quan doi|phien quan|csgt|canh sat|nhat ky 141|công an|tù nhân|giang hồ|lê thẩm dương|giết người|cướp của|cướp tài sản|bốc đầu|đánh ghen|đánh nhau|chém nhau|ngáo đá|ăn trộm|ăn cướp|say xỉn|chống đối|chống người|ô tô đâm|đẫm máu|cháy|tàu chiến|tên lửa|cãi nhau|hành hạ|giao thông|vụ tai nạn|băng cướp|tự tử' },
  { _id: "b4", uname: "dong-vat",         name: "Động vật",          pattern: 'động vật|chó|mèo|cờ hó|dog|khỉ|voi|ngựa|rắn|pet|con vật|con thú|sư tử|bạch tuộc|chim|thằn lằn|loại vật|tinh tinh|rết|hải sâm|cá mập' },
  { _id: "b5", uname: "game",             name: "Game",              pattern: 'crossfire|nfs|rengar|đế chế|gta|game|gameplay' },
  { _id: "b6", uname: "game-show",        name: "Game show",         pattern: 'thách thức danh hài|danh hài đất việt|cười xuyên việt' },
  { _id: "b7", uname: "han-quoc",         name: "Hàn quốc",          pattern: 'korea|han\\s?quoc|han\\s?xeng' },
  { _id: "b8", uname: "khoa-hoc",         name: "Khoa học",          pattern: 'khoa học|vũ trụ|nasa' },
  { _id: "b9", uname: "kpop",             name: "Kpop",              pattern: 'kpop' },
  { _id: "b0", uname: "lol",              name: "LOL",               pattern: 'lol|league of legends|liên minh huyền thoại|azir|yasuo|rengar|jinx|vayne|leblanc|ashe|ekko|faker|karthus|trundle|Teemo|wukong|Graves Montage|outplays?|Riot' },  
  { _id: "c1", uname: "nghe-thuat",       name: "Nghệ thuật",        pattern: 'bartender|nghệ thuật|hiphop|bboy|vẽ|múa|trống|hip hop|beatbox|slow motion|smoke tricks' },
  { _id: "c2", uname: "nguoi-bi-an",      name: "Người bí ẩn",       pattern: 'nguoi bi an' },
  { _id: "c3", uname: "nhat-ban",         name: "Nhật bản",          pattern: 'nhat ban|japan' },
  { _id: "c4", uname: "nonstop",          name: "Nonstop",           pattern: 'non\\s?stop' },
  { _id: "c5", uname: "phap-luat",        name: "Pháp luật",         pattern: 'cong an|canh sat' },
  { _id: "c6", uname: "phim-hai",         name: "Phim hài",          pattern: 'cười thả ga|faptv|hài nhật bản|vitamin k|đông hiếp|hài hàn quốc|gặp nhau để cười|phim ngắn mốc meo|việt hương|chí tài|hoài linh|phim.*?hài|phim.*?hai|Để Hội Hack' },
  { _id: "c7", uname: "phim-ngan",        name: "Phim ngắn",         pattern: 'phim|nhật ký sa tăng|film' }            ,
  { _id: "c8", uname: "phim-vo-thuat",    name: "Phim võ thuật",     pattern: 'lý tiểu long|chung tử đơn|lý liên kiệt|thành long|jason staham|tony jaa|ngô kinh|đấu võ|võ đài|phim võ thuật|phim hành động|thủy hử|lương sơn bạc|cao thủ|võ lâm|tịnh tà kiếm phổ|dương quá|kim dung|quyết đấu|đông phương|lệnh hồ|nhậm ngã hành|nhậm doanh doanh|kiếm phổ|lộc đỉnh ký|Hiên Viên Kiếm|Thần công' },
  { _id: "c9", uname: "phong-trao",       name: "Phong trào",        pattern: '' },
  { _id: "c0", uname: "series-hai",       name: "Series hài",        pattern: 'troll|prank|siêu hài canada|những thằng nguy hiểm nhất hành tinh|tổng hợp những pha|tuyển tập những thằng|tổng hợp những màn|funny video(s?)|hài hước|mắc cười|prank|Những thằng nghịch ngu nhất|pranks' },
  { _id: "d1", uname: "thai-lan",         name: "Thái lan",          pattern: 'thai lan|thailand' },
  { _id: "d2", uname: "the-thao",         name: "Thể thao",          pattern: 'bóng rổ|bong ro|bóng bàn|bong ban|tennis|cầu lông|cau long|quần vợt|quan vot|chạy bộ|penalty|trượt tuyết|truot tuyet|chạy thi|thi chạy|parkour|ném dao|thể thao|drift|vận động viên|skate ?boarding|mao hiem' },
  { _id: "d4", uname: "the-voice",        name: "The voice",         pattern: 'the\\s?voice' },
  { _id: "d5", uname: "trung-quoc",       name: "Trung Quốc",        pattern: 'trung quoc|china|chinese' },
  { _id: "d6", uname: "us",               name: "US",                pattern: 'us|america' },
  { _id: "d7", uname: "viet-nam",         name: "Việt Nam",          pattern: 'viet\\s?nam' },
  { _id: "d8", uname: "vlog",             name: "Vlog",              pattern: 'vlog|vinh râu|phở đặc biệt|Nghịch \\d+' },
  { _id: "d9", uname: "vo-thuat",         name: "Võ thuật",          pattern: 'karate|takewondo|võ sĩ|diễn võ thuật|wwe|thiếu lâm|võ thuật|múa kiếm' },
  { _id: "d0", uname: "vpop",             name: "VPop",              pattern: 'vpop' },
  { _id: "e1", uname: "got-talent",       name: "Got talent",        pattern: 'talent|gottalent' },
  { _id: "e2", uname: "xfactor",          name: "XFactor",           pattern: 'x\\s?factor|nhân tố bí ẩn' },
  { _id: "e3", uname: "y-nghia",          name: "Ý nghĩa",           pattern: 'cảm động|ý nghĩa|quà tặng cuộc sống|lòng tốt|tấm lòng' }
];